### ISSUE TITLE
How serialise indenting works

### ISSUE THREAD

**Issue by hxhieu** [smourier/ZeroDepJson#1]
Hi, 

Thanks for the lib but I am still struggling how to serialise to string with indents?
We also manually edit JSON files (configure files )so we would like to have user friendly indenting.

**Comment by smourier** [comment]
Hi,

You can just use one of the "SerializeFormatted" methods, for example:

	using System;
	using System.Collections.Generic;
	using System.IO;
	using System.Text;
	using ZeroDep;

	namespace ZeroDepJsonCore
	{
		class Program
		{
			static void Main(string[] args)
			{
				var dic = new Dictionary<Guid, Customer>();
				for (var i = 0; i < 2; i++)
				{
					var customer = new Customer();
					customer.Index = i;
					customer.Name = "This is a name 这是一个名字" + Environment.TickCount;
					var address1 = new Address();
					address1.ZipCode = 75000;
					address1.City = new City();
					address1.City.Name = "Paris";
					address1.City.Country = new Country();
					address1.City.Country.Name = "France";

					var address2 = new Address();
					address2.ZipCode = 10001;
					address2.City = new City();
					address2.City.Name = "New York";
					address2.City.Country = new Country();
					address2.City.Country.Name = "USA";

					customer.Addresses = new[] { address1, address2 };

					dic[customer.Id] = customer;
				}

				// serialize formatted to a stream
				using (var writer = new StreamWriter("test.json", false, Encoding.UTF8))
				{
					Json.SerializeFormatted(writer, dic);
				}
				
				// serialize formatted to a string
				Console.WriteLine(Json.SerializeFormatted(dic));
			}
		}

		public class Customer
		{
			public Customer()
			{
				Id = Guid.NewGuid();

			}

			public Guid Id { get; }
			public int Index { get; set; }
			public string Name { get; set; }

			public Address[] Addresses { get; set; }

			public override string ToString() => Name;
		}

		public class Address
		{
			public City City { get; set; }
			public int ZipCode { get; set; }

			public override string ToString() => ZipCode.ToString();
		}

		public class City
		{
			public string Name { get; set; }
			public Country Country { get; set; }

			public override string ToString() => Name;
		}

		public class Country
		{
			public string Name { get; set; }

			public override string ToString() => Name;
		}
	}

Will produce this JSON

	{
	 "c5b4091c-f97d-4828-9c5b-762fdfebc256": {
	   "Name": "This is a name 这是一个名字9414546",
	   "Addresses": [
		 {
		  "City": {
			"Name": "Paris",
			"Country": {
			  "Name": "France"
			 }
		   },
		  "ZipCode": 75000
		 },
		 {
		  "City": {
			"Name": "New York",
			"Country": {
			  "Name": "USA"
			 }
		   },
		  "ZipCode": 10001
		 }
		]
	  },
	 "3813c285-1c5d-48cf-8460-9ac2ad7cbcd9": {
	   "Index": 1,
	   "Name": "This is a name 这是一个名字9414546",
	   "Addresses": [
		 {
		  "City": {
			"Name": "Paris",
			"Country": {
			  "Name": "France"
			 }
		   },
		  "ZipCode": 75000
		 },
		 {
		  "City": {
			"Name": "New York",
			"Country": {
			  "Name": "USA"
			 }
		   },
		  "ZipCode": 10001
		 }
		]
	  }
	}

Note however that the implementation of SerializeFormatted is not optimal (it serializes and deserializes), the rationale being these methods are supposedly used more for debugging scenarios.

**Comment by hxhieu** [comment]
Cool thanks
