### ISSUE TITLE
More serialize and deserialize examples

### ISSUE THREAD

**Issue by Cale-Torino** [smourier/ZeroDepJson#2]
Hi there, Thanks for the useful class, just wondering if you can add some more serialize and deserialize examples?

I've used the method below but had issues with null exception handling since the error Json produces different json key-value pairs.

Would be nice if there were some Json formatted examples for easy understanding of the methods.

Example:

#### Normal response
```JSON
{
    "access_token": "asdfasdfsaf",
    "token_type": "bearer",
    "expires_in": 1658613850,
    "refresh_token": "asdfasfasfdsadf",
    "scope": "authorization,loginexample"
}
```

#### Error response
```JSON
{
    "error": "server_error",
    "error_description": "Invalid refresh token"
}
```

#### Example foreach loop
```C#
var list = Json.Deserialize<List<TokenLoginClass>>(JsonResult);
string access_token = "";
string token_type = "";
int expires_in = 0;
string refresh_token = "";
string scope = "";
string error = "";
string error_description = "";
foreach (var item in list)
{
    if (item.access_token != null)
    {
        access_token = item.access_token;
        token_type = item.token_type;
        expires_in = item.expires_in;
        refresh_token = item.refresh_token;
        scope = item.scope;
    }
    else
    {
        error = item.error;
        error_description = item.error_description;
    }
}
```

Thanks

**Comment by smourier** [comment]
Hi,

How do you define TokenLoginClass here and since you're deserializing as a list of TokenLoginClass, how is exactly the input json?

**Comment by smourier** [comment]
Closed for lack of activity.
