### ISSUE TITLE
Cyclic JSON serialization error on multiple refs of same object

### ISSUE THREAD

**Issue by shukriadams** [smourier/ZeroDepJson#3]
It looks like attempting to serialize a hierarchy of objects containing the same instance of an object either throws cyclic serialization exception, or serializes to null if I use JsonSerializationOptions.ContinueOnCycle. While I can understand that it doesn't make sense to serialize a hierarchy of where instance A contains a ref to B and B contains a ref to A, that is not happening in this case. A simple way to trigger this condition is to create a collection that has the same instance of any complex object added to it, even if that object contains only primitive properties. For example, this array can be properly serialized

    new string[]{ "foo", "foo" } 

but this array cannot

    class Person {
        public string Name {get;set;}
    }
    
    var person = new Person { Name = "foo"}
    new Person[] { person, person}

This seems to be because internally the objectGraph dictionary uses the object instance as key. If this is done as a safety feature to prevent infinite recursion it would be nice to use recursion depth count instead.

**Comment by smourier** [comment]
Hi,

The way it works currently is expected.

That being said, I've committed some changes https://github.com/smourier/ZeroDepJson/commit/1223111f13e6190e550667f26b115640e896ec60 that will allow you to customize how the object graph works.

You can now pass a custom object graph (it still has to derive from `IDictionary<object, object>` for compat reasons). And the `JsonOptions` object that's passed around has a `SerializationLevel` integer value.

So what you want can now be achieved like this for example:

    var person = new Person { Name = "foo" };
    var persons = new Person[] { person, person };
    var options = new CustomOptions();
    var json = Json.Serialize(persons, options);
    Assert.IsTrue(json == "[{\"Name\":\"foo\"},{\"Name\":\"foo\"}]");

    ....

    class CustomOptions : JsonOptions
    {
        public CustomOptions()
        {
            ObjectGraph = new CustomObjectGraph();
        }

        private class CustomObjectGraph : IDictionary<object, object>, Json.IOptionsHolder
        {
            private readonly Dictionary<object, int> _hash = new Dictionary<object, int>();

            // the options is set by the serializer
            public JsonOptions Options { get; set; }

            public void Add(object key, object value)
            {
                _hash[key] = Options.SerializationLevel;
            }

            public bool ContainsKey(object key)
            {
                if (!_hash.TryGetValue(key, out var level))
                    return false;

                if (Options.SerializationLevel == level)
                    return false;

                return true;
            }

            public object this[object key] { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
            public ICollection<object> Keys => throw new NotImplementedException();
            public ICollection<object> Values => throw new NotImplementedException();
            public int Count => throw new NotImplementedException();
            public bool IsReadOnly => throw new NotImplementedException();
            public void Add(KeyValuePair<object, object> item) => throw new NotImplementedException();
            public void Clear() => throw new NotImplementedException();
            public bool Contains(KeyValuePair<object, object> item) => throw new NotImplementedException();
            public void CopyTo(KeyValuePair<object, object>[] array, int arrayIndex) => throw new NotImplementedException();
            public IEnumerator<KeyValuePair<object, object>> GetEnumerator() => throw new NotImplementedException();
            public bool Remove(object key) => throw new NotImplementedException();
            public bool Remove(KeyValuePair<object, object> item) => throw new NotImplementedException();
            public bool TryGetValue(object key, [MaybeNullWhen(false)] out object value) => throw new NotImplementedException();
            IEnumerator IEnumerable.GetEnumerator() => throw new NotImplementedException();
        }
    }

**Comment by shukriadams** [comment]
Thanks, good to know there's a way around this. Closing ticket as it's not an issue.
