### ISSUE TITLE
may be bug

### ISSUE THREAD

**Issue by arcsin** [smourier/ZeroDepJson#4]
Hello, I need make json parser and I read you project. I think in function ReadX4 initialization "u" must be "1":
`private static ushort ReadX4(TextReader reader, JsonOptions options)
        {
            var u = 0;
            for (var i = 0; i < 4; i++)
            {
                u *= 16;
                if (reader.Peek() < 0)
                {
                    HandleException(new JsonException("JSO0008: JSON deserialization error detected at end of stream. Expecting hexadecimal character."), options);
                    return 0;
                }

                u += GetHexValue(reader, (char)reader.Read(), options);
            }
            return (ushort)u;
        }`

**Comment by smourier** [comment]
Hi,

Why would you want to do this?

This will add 0x10000 to the intermediary result (`u`), which will be truncated anyway since it's cast into `ushort` (16 bits) in the end.

**Comment by arcsin** [comment]
I am sorry. there are not mistakes
